### PR TITLE
Issue #8: Staggered data-structure code convention

### PR DESCRIPTION
**Pull request by Master-Foo**
Modified polls/admin.py to provide an example of staggered data-structure code convention

### CODE REVIEW

**Comment by FFX01** [comment]
I don't have any issues using this convention, but why did you remove the compiled python files from the gitignore?

**Comment by Master-Foo** [comment]
I think this convention should be flexible. If the data-structure is more than the width of the page (80 chars) stagger it.

I'm not sure what you are talking about. Can you link to the diff?

I don't think I removed _.pyc from the .gitignore. the only change I made was ~_ appended to the bottom. [Here](https://github.com/Master-Foo/Django-tut/blob/master/.gitignore) Is my fork which I pushed.

**Comment by FFX01** [comment]
Strange, the commit showed deletion of the lines in the gitignore, but maybe it just replaced the gitignore.

There's also now an issue with the merge since your branch has the db in it.

**Comment by Master-Foo** [comment]
I'll just delete my branch. Go ahead and ignore my pull request. It wasn't important, just an example of the code convention. I think you get the idea.

**Pull request closed without merging**
